Repository qri-io/qfs, pull requests merged in 2020-05, with the labels that each got.

#24 chore(deps): upgrade to go-ipfs 0.5.0
  .circleci/config.yml
  cafs/ipfs/config.go
  cafs/ipfs/coreunix/add.go
  cafs/ipfs/coreunix/add_test.go
  cafs/ipfs/init.go
  cafs/ipfs/migrate.go
  go.mod
  go.sum
Labels: chore

#25 feat(muxfs): take `MuxConfig` and return a Mux filesystem
  cafs/ipfs/config.go
  cafs/ipfs/config_test.go
  cafs/ipfs/coreunix/add_test.go
  cafs/ipfs/filestore.go
  cafs/ipfs/filestore_test.go
  cafs/ipfs/init.go
  cafs/ipfs_http/filestore.go
  cafs/ipfs_http/filestore_test.go
  fs.go
  fs_test.go
  go.mod
  go.sum
  httpfs/httpfs.go
  localfs/localfs.go
  localfs/localfs_test.go
  mem.go
  mux.go
  muxfs/mux.go
  muxfs/mux_test.go
Labels: refactor

#31 refactor(muxfs): add `GetHandler` and `GetResolver` functions
  cafs/mapstore.go
  fs.go
  fs_test.go
  muxfs/mux.go
  muxfs/mux_test.go
Labels: fix, refactor

#32 refactor(`RunMigrations`): func that copies, migrates, and moves the ipfs
  cafs/ipfs/config.go
  cafs/ipfs/config_test.go
  cafs/ipfs/migrate.go
  go.mod
  go.sum
Labels: refactor
